= AnsibleProject

== Organize Your Repository

Setup dedicated repository for your ansible projects, which includes playbooks, roles, and inventories. You might want to have a structure like this:

.Directory Structure
[source,shell]
----
.
├── inventories
│   ├── dev
│   ├── stage
│   └── produ
├── roles
├── playbooks
├── templates
└── ansible.cfg
----

This allows you to separate inventories for different environments, like development, staging, and production.

== Ansible Automation Platform

link:https://demo.redhat.com/catalog?item=babylon-catalog-prod/sandboxes-gpte.aap-product-demos.prod&utm_source=webapp&utm_medium=share-link[Red Hat AAP Sandbox]

.Specifications
* 1x Automation Controller on OCP4
* 1x OpenShift4 Cluster
* 1x RHEL8 Bastion Server w/ Anisble CLI tools
* AWS Open Environment for provisioning of resources needed for the demo

link:https://www.redhat.com/architect/ansible-automation-controller-cac-gitops[Config as Code - GitOps]

== Workflow

This repo currently offers a playbook that will configure controllers based on variables defined in group_vars.

. Ensure inventory.yml has YOUR Ansible Controller defined
. Create CONTROLLER_PASSWORD GitHub repository secret that is passed during workflow to run playbook agains inventory.yml
. Click Deploy button below and run workflow

image::https://github.com/r3dact3d/literate-doodle/actions/workflows/get-stats-workflow.yml/badge.svg[link="https://github.com/r3dact3d/literate-doodle/actions/workflows/get-stats-workflow.yml"]

NOTE: You can now check the Actions to watch/check the status of the deployment.


== Function

This will create admin credential, and a project with template to get stats from the controller.

    link:https://github.com/redhat-cop/controller_configuration.git
