---
controller_inventory_sources:
  - name: Windows Source
    source: scm
    source_path: inventories/static/demo.yml
    source_project: Windows Project
    inventory: windows_inventory
    description: created by Ansible controller
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
