---
controller_hostname: "{{ controller_host | default(groups['automationcontroller'][0]) }}"
controller_username: "{{ controller_user | default('admin') }}"
controller_validate_certs: false

ah_host: "{{ ah_hostname | default(groups['automationhub'][0]) }}:{{ ah_port | default(443) }}"
ah_username: "{{ ah_user | default('admin') }}"

ah_path_prefix: 'galaxy' # this is for private automation hub
ah_verify_ssl: false
ah_validate_certs: false

ee_registry_username: "{{ ah_username }}"
ee_registry_dest: "{{ ah_host }}"

eda_hostname: "{{ eda_host | default(groups['automationedacontroller'][0]) | default(groups['automationeda'][0]) }}:{{ eda_port | default(443) }}"
eda_username: "{{ eda_user | default('admin') }}"
eda_validate_certs: false

controller_password: "{{ controller_pass }}"
ah_password: "{{ controller_pass }}"
ee_registry_password: "{{ ah_password }}"
eda_password: "{{ controller_pass }}"

...
