---
controller_credentials:
  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: Default
    description: aap admin account
    inputs:
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"
      verify_ssl: false

  - name: root
    credential_type: Machine
    organization: Default
    description: root local password
    inputs:
      username: root
      password: "{{ controller_password }}"

  - name: CaC_seed_pat
    credential_type: GitHub Personal Access Token
    organization: Default
    description: config as code seed pat
    inputs:
      token: "{{ github_cac_pat }}"

...
