---
controller_templates_all:
  - name: controller_config
    project: config_as_code
    job_type: run
    playbook: playbooks/controller_config.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    verbosity: 0
    webhook_service: 'github'
    webhook_credential: CaC_seed_pat
    credentials:
      - aap_admin
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true
...