---
controller_projects:
  - name: Ansible Project
    description: config as code demo project
    organization: Linux
    scm_type: git
    scm_url: https://github.com/r3dact3d/AnsibleProject.git
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: false
    scm_credential: ""
