---
controller_templates:
  - name: Get Stats JT
    credentials:
      - aap_admin
    job_type: run
    inventory: dev_inventory
    project: Get Controller Stats Dev
    playbook: getControllerStats.yml
    ask_variables_on_launch: true
    extra_vars:
      controller_hostname:
      controller_password:
  - name: Copy SSH Key
    credentials:
      - aap_admin
    job_type: run
    inventory: dev_inventory
    project: Ansible Plays for Dev
    playbook: copySSHKey.yml
  - name: Dynamic Inventory
    credentials:
      - aap_admin
    job_type: run
    inventory: dev_inventory
    project: Ansible Plays for Dev
    playbook: dynamicInventory.yml
 
  - name: Get Sys Data
    job_type: run
    inventory: dev_inventory
    project: Ansible Use Cases
    playbook: Dynamic Inventory in Ansible Automation Platform/get_sys_data.yml


  - name: Terraform Init and Plan
    job_type: run
    inventory: Controller Inventory
    project: Urban Terraform
    playbook: playbooks/tf_init_plan.yml
    execution_environment: terraform-ee-base
    use_fact_cache: yes
    extra_vars: ''
  - name: Terraform Load and Apply
    job_type: run
    inventory: Controller Inventory
    project: Urban Terraform
    playbook: playbooks/tf_apply_plan.yml
    execution_environment: terraform-ee-base
    extra_vars: ''
    use_fact_cache: yes
  - name: RHEL Update
    credentials:
      - AWS
      - Demo Credential
    job_type: run
    inventory: dev_inventory
    project: Terraform Infra
    playbook: rhel_update.yml
...
