---
- name: Playbook to configure ansible controller post installation
  hosts: all
  connection: local
  tasks:
    

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
...